#!/usr/bin/env cmsRun
import FWCore.ParameterSet.Config as cms

process = cms.Process("treeCreatingSDecay")

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

process.load("Configuration.Geometry.GeometryRecoDB_cff")
process.load("Configuration.StandardSequences.MagneticField_cff")
process.load('Configuration.StandardSequences.Services_cff')
process.load('SimGeneral.HepPDTESSource.pythiapdt_cfi')
process.load('FWCore.MessageService.MessageLogger_cfi')
process.load('Configuration.EventContent.EventContent_cff')
process.load('Configuration.StandardSequences.GeometryRecoDB_cff')
process.load('Configuration.StandardSequences.MagneticField_AutoFromDBCurrent_cff')
process.load('Configuration.StandardSequences.EndOfProcess_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_condDBv2_cff')
process.load("TrackingTools/TransientTrack/TransientTrackBuilder_cfi")

process.MessageLogger.cerr.FwkReport.reportEvery = 1000

process.source = cms.Source("PoolSource",fileNames = cms.untracked.vstring(
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-1.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-10.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-11.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-12.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-13.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-14.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-15.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-16.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-17.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-18.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-19.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-2.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-20.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-21.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-22.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-23.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-24.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-25.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-3.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-4.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-5.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-6.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-7.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-8.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1-9.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_1.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_10.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_100.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_102.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_103.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_104.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_105.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_106.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_107.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_108.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_109.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_11.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_110.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_111.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_112.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_113.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_114.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_115.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_116.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_117.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_118.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_119.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_12.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_120.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_121.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_122.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_123.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_124.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_125.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_126.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_127.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_128.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_129.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_13.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_130.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_131.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_132.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_133.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_134.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_135.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_136.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_137.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_138.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_139.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_14.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_140.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_141.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_142.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_143.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_144.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_145.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_146.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_147.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_148.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_149.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_15.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_150.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_151.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_152.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_153.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_154.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_155.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_156.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_157.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_158.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_159.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_16.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_160.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_161.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_162.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_163.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_164.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_165.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_166.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_167.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_168.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_169.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_17.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_170.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_171.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_172.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_173.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_174.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_175.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_176.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_177.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_178.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_179.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_18.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_180.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_181.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_19.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-1.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-10.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-11.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-12.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-13.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-2.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-3.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-4.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-5.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-6.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-7.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-8.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2-9.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_2.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_20.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_22.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_23.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_24.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_25.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_26.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_27.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_28.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_29.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_3-1.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_3-2.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_3-3.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_3.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_30.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_32.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_33.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_34.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_35.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_36.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_37.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_38.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_39.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_4.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_40.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_41.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_42.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_43.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_45.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_47.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_5.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_50.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_51.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_52.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_53.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_54.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_55.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_56.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_57.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_58.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_59.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_6.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_60.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_61.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_62.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_63.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_64.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_65.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_67.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_68.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_69.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_7.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_70.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_71.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_72.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_73.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_74.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_75.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_76.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_77.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_78.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_79.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_8.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_80.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_81.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_82.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_83.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_84.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_86.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_87.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_88.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_89.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_9.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_90.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_91.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_92.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_93.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_94.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_95.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_96.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_97.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_98.root",
"file:///home/ltsai/Data/CRABdata/CRABdata_12_Sep_2018_pnLbTk_2016RunB_EDProducer/recoBPHanalysis_withFilter_99.root",
))

from Configuration.AlCa.GlobalTag_condDBv2 import GlobalTag
#process.GlobalTag = GlobalTag(process.GlobalTag, 'auto:run2_mc', '')
process.GlobalTag = GlobalTag(process.GlobalTag, '80X_dataRun2_2016LegacyRepro_v3', '')
#process.GlobalTag = GlobalTag(process.GlobalTag, '94X_dataRun2_ReReco_EOY17_v1', '')

process.TFileService = cms.Service('TFileService',
  fileName = cms.string('treeCreatingSpecificDecay_2016RunB.root'),
  closeFileFast = cms.untracked.bool(True)
)

process.treeCreatingSpecificDecay = cms.EDAnalyzer('treeCreatingSpecificDecay',
    oniaCandsLabel = cms.string("lbWriteSpecificDecay:oniaFitted:bphAnalysis"),
    pTksCandsLabel = cms.string("lbWriteSpecificDecay:pTksFitted:bphAnalysis"),
    pL0BCandsLabel = cms.string("lbWriteSpecificDecay:pL0BFitted:bphAnalysis"),
    nTksCandsLabel = cms.string("lbWriteSpecificDecay:nTksFitted:bphAnalysis"),
    nL0BCandsLabel = cms.string("lbWriteSpecificDecay:nL0BFitted:bphAnalysis"),
      bsPointLabel = cms.string("offlineBeamSpot::RECO")
)

process.p = cms.Path(
    process.treeCreatingSpecificDecay
)


